DenverCoder1/latex-gboard-dictionary

dictionary.txt

@DenverCoder1 Another one for hacktober-fest, please label it as hacktoberfest-accepted. Very happy to contribute in this project.

Update dictionary.txt, added silcrow/section sign 

---

dictionary.txt

@DenverCoder1 please merge it as another "hacktoberfest-accepted" label. 😄

Added Triangles symbol

---

dictionary.txt

Ref: Issue #13
Note: More shortcuts can be added to improve on the solution to this issue

Added replacements for non-alphanumeric shortcuts

---

README.md

I'm not much of a video watcher for tutorials but having a quick section on how it's used might be nice :)

Adds a brief line on usage to the readme

---

README.md

docs: Added usage gif

---

dictionary.txt

Add dagger symbol

---

dictionary.txt

\nsubset	⊄	
\notsubset	⊄	
\not\supset	⊅	
\not\supset	⊅

Added \nsubset \notsubset \nsupset \notsupset shortcuts

---

dictionary.txt

add smalltilde

---

dictionary.txt

Signed-off-by: Yash Prakash <yash2002109@gmail.com>

Add 'gimel' symbol to dictionary.txt

---

dictionary.txt

Removed the duplicate, and changed /sec to /S

changed \sec to \S

---

dictionary.txt

Added cancer symbol

---

dictionary.txt

Added Symbol C/o aka Care of

---

dictionary.txt

Please check and tell me if there are any errors

added aries symbol

---

dictionary.txt

Logical or with Double Overbar - [Unicode Char Table](https://unicode-table.com/en/2A62/)
Logical and with Double Overbar - [Unicode Char Table](https://unicode-table.com/en/2A5E/)

Added Logical And Double Overbar , Logical Or Double Overbar

---

dictionary.txt

Closed a previous PR with ohm because i had taken an inverted ohm symbol

added ohm to the dictionary

---

dictionary.txt

Signed-off-by: Yash Prakash <yash2002109@gmail.com>

Add 'sqcup' symbol to dictionary.txt

---

dictionary.txt

Signed-off-by: Eshaan Agarwal <eshaan060202@gmail.com>

add 7 greek letters

---

.github/lint

Fix line numbers in lint script

---

dictionary.txt

added dalet ℸ smbol to dictionary

---

dictionary.txt

Added Right Angle symbol

---

dictionary.txt

Currency Symbols Added

---

dictionary.txt

Added Star Equals symbol

---

dictionary.txt

Update dictionary.txt . . . adding Phi

---

dictionary.txt

Files changes:  dictionary.txt 
Changes :  Added 1 Mathematical logic proof symbol from #69 
Do let me know incase of any issue.

Adding Mathematical logic proof symbol from #69

---

dictionary.txt

Added swastika and reverse swastika sign (not available on google keyboard)

feat: Added swastika and revSwastika
